name: Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+"
jobs:

  CreateRelease:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          make_latest: true

  Release:
    needs: [CreateRelease]
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: build llvm
        run: docker build -t revive-llvm:latest --progress=plain -f --build-arg RUST_VERSION=1.80 .github/Dockerfile-llvm

      - name: build revive
        run: docker build -t revive:latest --progress=plain -f .github/Dockerfile

      - name: get binary
        run: docker run --rm revive:latest -v output:/app/output cp /app/release/revive/resolc /app/output

      # docker push revive:latest

      - run: gh release upload ${{ github.ref_name }} output/resolc --clobber
